include ../rules.mk

all: annealing.o dstfunc.o

annealing.o: 
	$(CPP) -c $(FLAG) ./cpp/annealing.cpp -o ../bin/annealing.o

dstfunc.o: 
	$(CPP) -c $(FLAG) ./cpp/dstfunc.cpp -o ../bin/dstfunc.o